name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install root dependencies
      run: npm install

    - name: Install frontend dependencies
      run: cd frontend && npm install

    - name: Install functions dependencies
      run: cd functions && npm install

    - name: Build frontend
      run: cd frontend && npm run build

    - name: Build functions
      run: cd functions && npm run build

    - name: Setup Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_PROJECT_ID }}"
      env:
        FIREBASE_CLI_EXPERIMENTS: webframeworks
